apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-frontend
  namespace: auction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-frontend
  template:
    metadata:
      labels:
        app: auction-frontend
    spec:
      containers:
        - name: auction-frontend
          image: mp5698/auction-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80