apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auction-ingress
  namespace: auction
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: auctionapp.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auction-frontend
                port:
                  number: 80
    - host: api.auctionapp.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 6001
